name: Build image using Dockerfile
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven'
        server-id: github
        server-username: GH_PACKAGES_USER
        server-password: GH_PACKAGES_TOKEN


    - name: Build container image
      run: mvn -B package
      env:
        GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
        GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

    - name: Read project version from pom.xml
      run: |
        echo "IMAGE_TAG=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
