# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and push image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:


    - uses: actions/checkout@v3

    - name: Get short version of sha
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: github
        server-username: GH_PACKAGES_USER
        server-password: GH_PACKAGES_TOKEN

    - name: Build project
      run: mvn -B package
      env:
        GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
        GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

    - name: Prepare Docker metadata
      if: github.event_name != 'pull_request'
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/joakimen/java-gha-ci
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=raw,value=${{ steps.vars.outputs.sha_short }}-${{ github.run_id }}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Login to ghcr.io
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
