# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: github
        server-username: GH_PACKAGES_USER
        server-password: GH_PACKAGES_TOKEN

    - name: maven - build
      run: mvn -B package --file pom.xml
      env:
        GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
        GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

    - name: maven - prepare release
      run: mvn -B release:prepare
      env:
        GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
        GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

    - name: maven - perform release
      run: mvn -B release:perform
      env:
        GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
        GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
